# file: btv.yml
---
- name: Install my tools
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - role: V01dDweller.vim_install
      tags: vim
      become: true

    - role: vim_addons
      tags: vim

    - role: V01dDweller.tmux_install
      tags: tmux
      become: true

    - role: nodejs_install
      tags:
        - node
        - nodejs

    - role: tmux_addons
      tags: tmux

  post_tasks:
    - name: Copying bash files
      ansible.builtin.copy:
        src: bash/{{ item }}
        dest: ~/{{ item }}
        mode: '0644'
      loop:
        - .LESS_TERMCAP
        - .bash_profile
        - .bash_prompt.sh
        - .bashrc
      tags:
        - bash
...
# vim: ft=ansible syntax=yaml.ansible nu nowrap relativenumber colorcolumn=80
