# file: btv.yml
---
- name: Install my tools
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    node_version: 19
    vim_pack_dir: ~/.vim/pack/coc/start
  roles:
    - role: V01dDweller.vim_install
      tags: vim
      become: true

    - role: V01dDweller.tmux_install
      tags: tmux
      become: true

  post_tasks:
    - name: Installing NodeJS repo
      ansible.builtin.shell: |
        set -o pipefail
        curl -fsSL https://deb.nodesource.com/setup_{{ node_version }}.x | bash
      args:
        executable: /bin/bash
        creates: /etc/apt/sources.list.d/nodesource.list
      become: true
      tags: node

    - name: Installing NodeJS {{ node_version }}
      ansible.builtin.apt:
        name: nodejs
        state: present
        update_cache: true
      become: true
      tags: node

    - name: Creating {{ vim_pack_dir }}
      ansible.builtin.file:
        path: '{{ vim_pack_dir }}'
        state: directory
        mode: 0755

    - name: Cloning Coc repo
      ansible.builtin.git:
        repo: https://github.com/neoclide/coc.nvim.git
        depth: 1
        version: release
        dest: '{{ vim_pack_dir }}/coc.nvim'
      tags:
        - coc
        - vim

    - name: Installing vim-coc plugin
      ansible.builtin.shell: |
        set -o pipefail
        /usr/local/bin/vim -c "helptags coc.nvim/doc/ | q"
      args:
        chdir: '{{ vim_pack_dir }}'
        executable: /bin/bash
        creates: ~/.config/coc/extensions/package.json
      tags:
        - coc
        - vim

    - name: Creating Vim directories
      ansible.builtin.file:
        path: ~/.vim/{{ item }}
        state: directory
        mode: 0755
      loop:
        - autoload
        - bundle
        - colors
      tags:
        - vim
        - colors
        - plugins

    - name: Downloading Pathogen from GitHub
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/tpope/vim-pathogen/master/\
              autoload/pathogen.vim"
        dest: ~/.vim/autoload/pathogen.vim
      tags:
        - vim
        - plugins

    - name: Creating list of vim plugins
      ansible.builtin.set_fact:
        vim_plugins:
          - {repo: 'dense-analysis/ale', version: 'master'}
          - {repo: 'vim-scripts/AnsiEsc.vim', version: 'master'}
          - {repo: 'pearofducks/ansible-vim', version: 'master'}
          - {repo: 'vim-airline/vim-airline', version: 'master'}
          - {repo: 'vim-airline/vim-airline-themes', version: 'master'}
          - {repo: 'chrisbra/Colorizer', version: 'master'}
          - {repo: 'airblade/vim-gitgutter', version: 'master'}
          - {repo: 'jvirtanen/vim-hcl', version: 'main'}
          - {repo: 'martinda/Jenkinsfile-vim-syntax', version: 'master'}
          - {repo: 'PProvost/vim-ps1', version: 'master'}
          - {repo: 'tpope/vim-fugitive', version: 'master'}
          - {repo: 'tpope/vim-vinegar', version: 'master'}
          - {repo: 'chr4/nginx.vim', version: 'master'}
          - {repo: 'vim-scripts/delview', version: 'master'}
          - {repo: 'tommcdo/vim-lion', version: 'master'}
          - {repo: 'dracula/vim', version: 'master'}
          - {repo: 'preservim/nerdtree', version: 'master'}
          - {repo: 'edkolev/tmuxline.vim', version: 'master'}
          - {repo: 'edkolev/promptline.vim', version: 'master'}
          - {repo: 'tpope/vim-repeat', version: 'master'}
          - {repo: 'tpope/vim-surround', version: 'master'}
      tags:
        - vim
        - plugins

    - name: Creating list of Vim color schemes
      ansible.builtin.set_fact:
        vim_colors:
          - gosukiwi/vim-atom-dark/master/colors/atom-dark-256.vim
          - baskerville/bubblegum/master/colors/bubblegum-256-dark.vim
          - morhetz/gruvbox/master/colors/gruvbox.vim
          - micke/vim-hybrid/master/colors/hybrid.vim
          - tomasr/molokai/master/colors/molokai.vim
          - jalvesaq/southernlights/master/colors/southernlights.vim
          - vim-scripts/xoria256.vim/master/colors/xoria256.vim
          - wadackel/vim-dogrun/main/colors/dogrun.vim
          - NLKNguyen/papercolor-theme/master/colors/PaperColor.vim
      tags:
        - vim
        - colors

    - name: Cloning Vim plugins from git
      ansible.builtin.git:
        repo: https://github.com/{{ item.repo }}
        dest: ~/.vim/bundle/{{ item.repo | basename }}
        depth: 1
        version: '{{ item.version }}'
      loop: '{{ vim_plugins }}'
      loop_control:
        label: Cloning {{ item.repo | basename }}
      tags:
        - vim
        - plugins

    - name: Downloading Vim color schemes
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/{{ item }}
        dest: ~/.vim/colors/{{ item | basename }}
        mode: 0644
      loop: '{{ vim_colors }}'
      loop_control:
        label: Cloning {{ item | basename }}
      tags:
        - vim
        - colors

    - name: Copying .vimrc and .gvimrc
      ansible.builtin.copy:
        src: vim/{{ item }}
        dest: ~/{{ item }}
        mode: 0644
      loop:
        - .vimrc
        - .gvimrc
      tags:
        - vim

    - name: Copying bash files
      ansible.builtin.copy:
        src: bash/{{ item }}
        dest: ~/{{ item }}
      loop:
        - .LESS_TERMCAP
        - .bash_profile
        - .bash_prompt.sh
        - .bashrc
      tags:
        - bash

    - name: Creating ~/.tmux directory
      ansible.builtin.file:
        path: ~/.tmux/plugins
        state: directory
        mode: 0755
      tags:
        - tmux

    - name: Cloning tpm plugin from GitHub
      ansible.builtin.git:
        repo: https://github.com/tmux-plugins/tpm
        dest: ~/.tmux/plugins/tpm
      tags:
        - tmux

    - name: Copying Tmux files
      ansible.builtin.copy:
        src: tmux/{{ item }}
        dest: ~/{{ item }}
      loop:
        - .tmux.clipboard.conf
        - .tmux.conf
      tags:
        - tmux


...
