# file: roles/nodejs_install/tasks/almalinux.yml
---
- name: Installing NodeJS
  ansible.builtin.dnf:
    name: '@nodejs:{{ node_version }}'
    state: present
  become: true
...
# vim: filetype=ansible syntax=yaml.ansible number relativenumber colorcolumn=80
